Basiacarvalho/feature/search page
filip-bak/so-yummy-project pull request #3
Opened 2023-10-27 19:16 UTC by basiacarvalho

Cześć, przesyła responsywny layout dla SearchPage dla pierwszego wejścia użytkownika (bez wyników wyszukiwania). Nazwy 3 głównych komponentów  ("MainPageTitle" / "SearchBar" / "SearchedRecipesList") są zgodnie z wytycznymi, a te mają w sobie mniejsze (często "ponownie używalne" komponenty w innych częściach aplikacji, jak na przykład "MainPageTitle" czy "NoContent"). Wymiary i stylizacja są zgodne z figmą oraz przykładową stronką. "Breakpointy" są trochę inne niż ostatnio w projekcie (375px / 768px / no i ten na desktop jest dość spory 1440px - ale, tak jest zgodnie z danym).

2023-10-27 20:01 UTC, filip-bak requested changes

2023-10-27 20:01 UTC, filip-bak commented on frontend/src/components/MainPageTitle/MainPageTitle.module.css
> +.element_one {
Zaimplementuj te elementy za pomocą 
`display: absolute `
i
`distplay: relative`

2023-10-28 10:58 UTC, basiacarvalho commented on frontend/src/components/MainPageTitle/MainPageTitle.module.css
> +.element_one {
Pozycjonowanie elementów zrobione :)

2023-10-28 16:04 UTC, filip-bak approved these changes

2023-10-28 16:04 UTC, merged